language: node_js
node_js:
  - "10"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - ng build --prod

after_success:
  - test $TRAVIS_PULL_REQUEST = "false" && firebase deploy --project notes-14a4a --token $FIREBASE_TOKEN
